name: Mastodon Scraping Sync with SAS Token

on:
  schedule:
   # - cron: "*/10 * * * *"  # Runs every 10 minutes
     - cron: "0 * * * *"  # Runs every 1 hour
  workflow_dispatch:  # Allows manual triggering if needed

jobs:
  check_and_upload:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install azure-storage-blob requests

      - name: Run upload script
        env:
          GH_REPO: ${{ secrets.GH_REPO }}
          FILE_PATH: ${{ secrets.FILE_PATH }}
          AZURE_BLOB_URL: ${{ secrets.AZURE_BLOB_URL }}
          AZURE_SAS_TOKEN: ${{ secrets.AZURE_SAS_TOKEN }}
        run: python upload_instances.py
